//
// Created by dkuch on 07.02.2020.
//

#ifndef TIME_INTERVAL_SUM_SERVER_NUMBERSSTREAMPARSER_H
#define TIME_INTERVAL_SUM_SERVER_NUMBERSSTREAMPARSER_H

class NumbersStreamParser
{

};

#endif //TIME_INTERVAL_SUM_SERVER_NUMBERSSTREAMPARSER_H
